### ISSUE TITLE
Style and Branding for eLwazi catalogue

### ISSUE THREAD

**Issue by Wkt8** [ebi-ait/data-catalogue-frontend#41] opened 2024-04-23 12:35 UTC
Add eLwazi colors and logos (Branding information here: https://drive.google.com/drive/folders/1QYt6Dfwprqz9Jym7Ye-DQYdellSJeT4G)

 Example: http://154.114.10.189/

**Comment by amnonkhen** [comment] 2024-04-26 10:44
dupe of #40

**Closed as completed by amnonkhen** 2024-04-26 10:44 UTC
Labels: FAIRification, Data Catalogue, eLwazi
